name: Bench
on:
  push:
    branches: [ "main", "gitter499/in-progress-bench" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
env:
  CARGO_TERM_COLOR: always
jobs:
 build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: '${{ matrix.config.os }}'
    name: '${{ matrix.config.target }}'
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        rustup default nightly
    - name: benchmark
      run: ./xb bench
    - uses: actions/upload-artifact@v4
      with:
        name: bench-results
        path: tests/benches/results
